server:
  port: 2955

spring:
  datasource:
    username: root
    password: 5945
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.noahcode.blog.mapper

#showSql
logging:
  level:
    cn:
      noahcode:
        blog:
          mapper: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false
