server:
  port: 2955

spring:
  datasource:
    username: root
    password: 5945
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.noahcode.blog.po

#showSql
logging:
  level:
    com:
      example:
        mapper : debug